### ISSUE TITLE
npm install -g xc-cli not working on Windows 10 64-bit

### ISSUE THREAD

**Issue by healthcareguy** [xgenecloud/xgenecloud#5]
**Bug is in**
[ X] CLI
[ ] Desktop App
[ ] REST API Framework 
[ ] GraphQL API Framework

put letter x within relevant [ ] above

**Describe the bug**

**To Reproduce**
`npm install -g xc-cli`

**Expected behavior**
Success

**Desktop (please complete the following information):**
 - CLI Version [e.g. 0.3.1]

**Additional context**
```
C:\Users\XXXX\AppData\Roaming\npm\node_modules\xc-cli\postInstall.js:35
})().catch(e => console.log(e)).finally(() => {
                                       ^

TypeError: (intermediate value)(...).catch(...).finally is not a function
    at Object.<anonymous> (C:\Users\XXXX\AppData\Roaming\npm\node_modules\xc-cli\postInstall.js:35:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xc-cli@0.3.2 postinstall: `node postInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xc-cli@0.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2020-06-10T02_28_13_501Z-debug.log
```

**Comment by healthcareguy** [comment]
Updated nodejs - works now
